python3 main_test.py \
--image_dir data/iu_xray/images/ \
--ann_path data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 1 \
--epochs 100 \
--save_dir medclip_mlc_n_lc050_lm050/ \
--step_size 50 \
--gamma 0.1 \
--seed 9223 \
--load medclip_mlc_n_lc050_lm050/current_checkpoint.pth